# Generated by Django 4.1.4 on 2022-12-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremierTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Club', models.CharField(max_length=200, unique=True)),
                ('MP', models.IntegerField(default=0)),
                ('W', models.IntegerField(default=0)),
                ('D', models.IntegerField(default=0)),
                ('L', models.IntegerField(default=0)),
                ('GF', models.IntegerField(default=0)),
                ('GA', models.IntegerField(default=0)),
                ('GD', models.IntegerField(default=0)),
                ('Pts', models.IntegerField(default=0)),
            ],
        ),
    ]
